/**
 * generated by Xtext 2.28.0
 */
package org.emoflon.ibex.tgg.integrate.integrate;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pipeline Stage Count</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.emoflon.ibex.tgg.integrate.integrate.IntegratePackage#getPipelineStageCount()
 * @model
 * @generated
 */
public interface PipelineStageCount extends PipelineStageEnd
{
} // PipelineStageCount
