/**
 * generated by Xtext 2.27.0
 */
package org.emoflon.ibex.tgg.integrate.integrate;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Resolution Strategy With Operational Delta</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.ibex.tgg.integrate.integrate.ResolutionStrategyWithOperationalDelta#getStrategy <em>Strategy</em>}</li>
 *   <li>{@link org.emoflon.ibex.tgg.integrate.integrate.ResolutionStrategyWithOperationalDelta#getOperationalDelta <em>Operational Delta</em>}</li>
 * </ul>
 *
 * @see org.emoflon.ibex.tgg.integrate.integrate.IntegratePackage#getResolutionStrategyWithOperationalDelta()
 * @model
 * @generated
 */
public interface ResolutionStrategyWithOperationalDelta extends EObject
{
  /**
   * Returns the value of the '<em><b>Strategy</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Strategy</em>' containment reference.
   * @see #setStrategy(ResolutionStrategy)
   * @see org.emoflon.ibex.tgg.integrate.integrate.IntegratePackage#getResolutionStrategyWithOperationalDelta_Strategy()
   * @model containment="true"
   * @generated
   */
  ResolutionStrategy getStrategy();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.tgg.integrate.integrate.ResolutionStrategyWithOperationalDelta#getStrategy <em>Strategy</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Strategy</em>' containment reference.
   * @see #getStrategy()
   * @generated
   */
  void setStrategy(ResolutionStrategy value);

  /**
   * Returns the value of the '<em><b>Operational Delta</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operational Delta</em>' containment reference.
   * @see #setOperationalDelta(OperationalDelta)
   * @see org.emoflon.ibex.tgg.integrate.integrate.IntegratePackage#getResolutionStrategyWithOperationalDelta_OperationalDelta()
   * @model containment="true"
   * @generated
   */
  OperationalDelta getOperationalDelta();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.tgg.integrate.integrate.ResolutionStrategyWithOperationalDelta#getOperationalDelta <em>Operational Delta</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operational Delta</em>' containment reference.
   * @see #getOperationalDelta()
   * @generated
   */
  void setOperationalDelta(OperationalDelta value);

} // ResolutionStrategyWithOperationalDelta
