/**
 * generated by Xtext 2.25.0
 */
package org.emoflon.ibex.tgg.integrate.integrate;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Revoke Deletion Resolution Strategy</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.emoflon.ibex.tgg.integrate.integrate.IntegratePackage#getRevokeDeletionResolutionStrategy()
 * @model
 * @generated
 */
public interface RevokeDeletionResolutionStrategy extends ResolutionStrategy
{
} // RevokeDeletionResolutionStrategy
