/**
 * generated by Xtext 2.26.0
 */
package org.emoflon.ibex.tgg.integrate.integrate.impl;

import org.eclipse.emf.ecore.EClass;

import org.emoflon.ibex.tgg.integrate.integrate.DeleteCorrespondencesResolutionStrategy;
import org.emoflon.ibex.tgg.integrate.integrate.IntegratePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Delete Correspondences Resolution Strategy</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DeleteCorrespondencesResolutionStrategyImpl extends FallbackResolutionStrategyImpl implements DeleteCorrespondencesResolutionStrategy
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeleteCorrespondencesResolutionStrategyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IntegratePackage.Literals.DELETE_CORRESPONDENCES_RESOLUTION_STRATEGY;
  }

} //DeleteCorrespondencesResolutionStrategyImpl
