/**
 * generated by Xtext 2.25.0
 */
package org.emoflon.ibex.tgg.integrate.integrate.impl;

import org.eclipse.emf.ecore.EClass;

import org.emoflon.ibex.tgg.integrate.integrate.IntegratePackage;
import org.emoflon.ibex.tgg.integrate.integrate.PipelineStageDeleted;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pipeline Stage Deleted</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PipelineStageDeletedImpl extends PipelineStageModificationImpl implements PipelineStageDeleted
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PipelineStageDeletedImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IntegratePackage.Literals.PIPELINE_STAGE_DELETED;
  }

} //PipelineStageDeletedImpl
