/*
 * generated by Xtext 2.27.0
 */
package org.emoflon.ibex.common.slimgt.validation;

import java.util.HashMap;
import java.util.Map;

import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EcorePackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.eclipse.emf.ecore.xmi.impl.EcoreResourceFactoryImpl;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.resource.XtextResourceSet;
import org.eclipse.xtext.validation.Check;
import org.emoflon.ibex.common.slimgt.slimGT.Import;
import org.emoflon.ibex.common.slimgt.slimGT.SlimGTPackage;

/**
 * This class contains custom validation rules.
 *
 * See
 * https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class SlimGTValidator extends AbstractSlimGTValidator {

	protected Map<Resource, Map<URI, Resource>> resourceCache = new HashMap<>();

	protected Resource loadResource(final Resource requester, final URI gtModelUri) {
		Map<URI, Resource> cache = resourceCache.get(requester);
		if (cache == null) {
			cache = new HashMap<>();
			resourceCache.put(requester, cache);
		}

		Resource other = cache.get(gtModelUri);
		if (other == null) {
			XtextResourceSet rs = new XtextResourceSet();
			try {
				other = rs.getResource(gtModelUri, true);
			} catch (Exception e) {
				return other;
			}
			cache.put(gtModelUri, other);

			if (other == null)
				return other;

			EcoreUtil2.resolveLazyCrossReferences(other, () -> false);
		}

		return other;
	}

	/**
	 * This prevents all exceptions being "swallowed" by the default validator
	 * implementation. TODO: Remove this or make it a little nice for future stable
	 * release candidates.
	 */
	@Override
	protected void handleExceptionDuringValidation(final Throwable targetException) throws RuntimeException {
		targetException.printStackTrace();
	}

	@Check
	protected void checkMetamodelImports(Import imp) {
		if(imp == null) {
			error("Expected an import URI after the import statement.", SlimGTPackage.Literals.IMPORT__NAME);
			return;
		}
		
		ResourceSet rs = new ResourceSetImpl();
		rs.getResourceFactoryRegistry().getExtensionToFactoryMap().put("ecore", new EcoreResourceFactoryImpl());
		EcorePackage.eINSTANCE.eClass();
		URI uri = URI.createURI(imp.getName().replace("\"", ""));
		Resource r = null;
		EPackage metaModel = null;
		try {
			r = rs.getResource(uri, true);
			metaModel = (EPackage) r.getContents().get(0);
		} catch (Exception e) {
			error("Exception ocurred while loading imported metamodel: " + e.getMessage(),
					SlimGTPackage.Literals.IMPORT__NAME);
			return;
		}

		if (metaModel == null)
			error("Imported metamodel could not be loaded.", SlimGTPackage.Literals.IMPORT__NAME);

	}

}
