/**
 * generated by Xtext 2.25.0
 */
package org.emoflon.ibex.gt.editor.gT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.AddExpression#getLeft <em>Left</em>}</li>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.AddExpression#getAddOperator <em>Add Operator</em>}</li>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.AddExpression#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getAddExpression()
 * @model
 * @generated
 */
public interface AddExpression extends ArithmeticExpression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(ArithmeticExpression)
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getAddExpression_Left()
   * @model containment="true"
   * @generated
   */
  ArithmeticExpression getLeft();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.gt.editor.gT.AddExpression#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(ArithmeticExpression value);

  /**
   * Returns the value of the '<em><b>Add Operator</b></em>' attribute.
   * The literals are from the enumeration {@link org.emoflon.ibex.gt.editor.gT.AddOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Add Operator</em>' attribute.
   * @see org.emoflon.ibex.gt.editor.gT.AddOperator
   * @see #setAddOperator(AddOperator)
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getAddExpression_AddOperator()
   * @model
   * @generated
   */
  AddOperator getAddOperator();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.gt.editor.gT.AddExpression#getAddOperator <em>Add Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Add Operator</em>' attribute.
   * @see org.emoflon.ibex.gt.editor.gT.AddOperator
   * @see #getAddOperator()
   * @generated
   */
  void setAddOperator(AddOperator value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(ArithmeticExpression)
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getAddExpression_Right()
   * @model containment="true"
   * @generated
   */
  ArithmeticExpression getRight();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.gt.editor.gT.AddExpression#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(ArithmeticExpression value);

} // AddExpression
