/**
 * generated by Xtext 2.27.0
 */
package org.emoflon.ibex.gt.editor.gT;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Editor Reference Iterator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.EditorReferenceIterator#getType <em>Type</em>}</li>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.EditorReferenceIterator#getName <em>Name</em>}</li>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.EditorReferenceIterator#getSubType <em>Sub Type</em>}</li>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.EditorReferenceIterator#getIteratorAttributes <em>Iterator Attributes</em>}</li>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.EditorReferenceIterator#getReferences <em>References</em>}</li>
 * </ul>
 *
 * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorReferenceIterator()
 * @model
 * @generated
 */
public interface EditorReferenceIterator extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(EReference)
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorReferenceIterator_Type()
   * @model
   * @generated
   */
  EReference getType();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.gt.editor.gT.EditorReferenceIterator#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(EReference value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorReferenceIterator_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.gt.editor.gT.EditorReferenceIterator#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Sub Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Type</em>' reference.
   * @see #setSubType(EClass)
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorReferenceIterator_SubType()
   * @model
   * @generated
   */
  EClass getSubType();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.gt.editor.gT.EditorReferenceIterator#getSubType <em>Sub Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub Type</em>' reference.
   * @see #getSubType()
   * @generated
   */
  void setSubType(EClass value);

  /**
   * Returns the value of the '<em><b>Iterator Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.emoflon.ibex.gt.editor.gT.EditorIteratorAttributeAssignment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iterator Attributes</em>' containment reference list.
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorReferenceIterator_IteratorAttributes()
   * @model containment="true"
   * @generated
   */
  EList<EditorIteratorAttributeAssignment> getIteratorAttributes();

  /**
   * Returns the value of the '<em><b>References</b></em>' containment reference list.
   * The list contents are of type {@link org.emoflon.ibex.gt.editor.gT.EditorIteratorReference}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>References</em>' containment reference list.
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorReferenceIterator_References()
   * @model containment="true"
   * @generated
   */
  EList<EditorIteratorReference> getReferences();

} // EditorReferenceIterator
