/**
 * generated by Xtext 2.27.0
 */
package org.emoflon.ibex.gt.editor.gT;

import org.eclipse.emf.ecore.EEnumLiteral;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Editor Enum Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.EditorEnumExpression#getLiteral <em>Literal</em>}</li>
 * </ul>
 *
 * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorEnumExpression()
 * @model
 * @generated
 */
public interface EditorEnumExpression extends EditorExpression
{
  /**
   * Returns the value of the '<em><b>Literal</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Literal</em>' reference.
   * @see #setLiteral(EEnumLiteral)
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorEnumExpression_Literal()
   * @model
   * @generated
   */
  EEnumLiteral getLiteral();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.gt.editor.gT.EditorEnumExpression#getLiteral <em>Literal</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Literal</em>' reference.
   * @see #getLiteral()
   * @generated
   */
  void setLiteral(EEnumLiteral value);

} // EditorEnumExpression
