/**
 * generated by Xtext 2.27.0
 */
package org.emoflon.ibex.gt.editor.gT;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Editor Iterator Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.EditorIteratorReference#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.EditorIteratorReference#getSource <em>Source</em>}</li>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.EditorIteratorReference#getType <em>Type</em>}</li>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.EditorIteratorReference#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorIteratorReference()
 * @model
 * @generated
 */
public interface EditorIteratorReference extends EObject
{
  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link org.emoflon.ibex.gt.editor.gT.EditorOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see org.emoflon.ibex.gt.editor.gT.EditorOperator
   * @see #setOperator(EditorOperator)
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorIteratorReference_Operator()
   * @model
   * @generated
   */
  EditorOperator getOperator();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.gt.editor.gT.EditorIteratorReference#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see org.emoflon.ibex.gt.editor.gT.EditorOperator
   * @see #getOperator()
   * @generated
   */
  void setOperator(EditorOperator value);

  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(EditorNode)
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorIteratorReference_Source()
   * @model
   * @generated
   */
  EditorNode getSource();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.gt.editor.gT.EditorIteratorReference#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(EditorNode value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(EReference)
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorIteratorReference_Type()
   * @model
   * @generated
   */
  EReference getType();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.gt.editor.gT.EditorIteratorReference#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(EReference value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(EditorReferenceIterator)
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorIteratorReference_Target()
   * @model
   * @generated
   */
  EditorReferenceIterator getTarget();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.gt.editor.gT.EditorIteratorReference#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(EditorReferenceIterator value);

} // EditorIteratorReference
