/**
 * generated by Xtext 2.27.0
 */
package org.emoflon.ibex.gt.editor.gT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Editor Parameter Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.EditorParameterExpression#getParameter <em>Parameter</em>}</li>
 * </ul>
 *
 * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorParameterExpression()
 * @model
 * @generated
 */
public interface EditorParameterExpression extends EditorExpression
{
  /**
   * Returns the value of the '<em><b>Parameter</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter</em>' reference.
   * @see #setParameter(EditorParameter)
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorParameterExpression_Parameter()
   * @model
   * @generated
   */
  EditorParameter getParameter();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.gt.editor.gT.EditorParameterExpression#getParameter <em>Parameter</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameter</em>' reference.
   * @see #getParameter()
   * @generated
   */
  void setParameter(EditorParameter value);

} // EditorParameterExpression
