/**
 * generated by Xtext 2.25.0
 */
package org.emoflon.ibex.gt.editor.gT;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Editor Attribute Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.EditorAttributeAssignment#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.EditorAttributeAssignment#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorAttributeAssignment()
 * @model
 * @generated
 */
public interface EditorAttributeAssignment extends EObject
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' reference.
   * @see #setAttribute(EAttribute)
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorAttributeAssignment_Attribute()
   * @model
   * @generated
   */
  EAttribute getAttribute();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.gt.editor.gT.EditorAttributeAssignment#getAttribute <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(EAttribute value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(EditorExpression)
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getEditorAttributeAssignment_Value()
   * @model containment="true"
   * @generated
   */
  EditorExpression getValue();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.gt.editor.gT.EditorAttributeAssignment#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(EditorExpression value);

} // EditorAttributeAssignment
