/**
 * generated by Xtext 2.25.0
 */
package org.emoflon.ibex.gt.editor.gT;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.emoflon.ibex.gt.editor.gT.GTPackage
 * @generated
 */
public interface GTFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GTFactory eINSTANCE = org.emoflon.ibex.gt.editor.gT.impl.GTFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Editor GT File</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor GT File</em>'.
   * @generated
   */
  EditorGTFile createEditorGTFile();

  /**
   * Returns a new object of class '<em>Editor Parameter Or Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Parameter Or Node</em>'.
   * @generated
   */
  EditorParameterOrNode createEditorParameterOrNode();

  /**
   * Returns a new object of class '<em>Editor Import</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Import</em>'.
   * @generated
   */
  EditorImport createEditorImport();

  /**
   * Returns a new object of class '<em>Editor Pattern</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Pattern</em>'.
   * @generated
   */
  EditorPattern createEditorPattern();

  /**
   * Returns a new object of class '<em>Editor Parameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Parameter</em>'.
   * @generated
   */
  EditorParameter createEditorParameter();

  /**
   * Returns a new object of class '<em>Editor Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Node</em>'.
   * @generated
   */
  EditorNode createEditorNode();

  /**
   * Returns a new object of class '<em>Editor Attribute Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Attribute Constraint</em>'.
   * @generated
   */
  EditorAttributeConstraint createEditorAttributeConstraint();

  /**
   * Returns a new object of class '<em>Editor Attribute Assignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Attribute Assignment</em>'.
   * @generated
   */
  EditorAttributeAssignment createEditorAttributeAssignment();

  /**
   * Returns a new object of class '<em>Editor Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Expression</em>'.
   * @generated
   */
  EditorExpression createEditorExpression();

  /**
   * Returns a new object of class '<em>Editor Attribute Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Attribute Expression</em>'.
   * @generated
   */
  EditorAttributeExpression createEditorAttributeExpression();

  /**
   * Returns a new object of class '<em>Editor Count Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Count Expression</em>'.
   * @generated
   */
  EditorCountExpression createEditorCountExpression();

  /**
   * Returns a new object of class '<em>Editor Literal Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Literal Expression</em>'.
   * @generated
   */
  EditorLiteralExpression createEditorLiteralExpression();

  /**
   * Returns a new object of class '<em>Editor Enum Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Enum Expression</em>'.
   * @generated
   */
  EditorEnumExpression createEditorEnumExpression();

  /**
   * Returns a new object of class '<em>Editor Parameter Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Parameter Expression</em>'.
   * @generated
   */
  EditorParameterExpression createEditorParameterExpression();

  /**
   * Returns a new object of class '<em>Editor Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Reference</em>'.
   * @generated
   */
  EditorReference createEditorReference();

  /**
   * Returns a new object of class '<em>Editor Reference Iterator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Reference Iterator</em>'.
   * @generated
   */
  EditorReferenceIterator createEditorReferenceIterator();

  /**
   * Returns a new object of class '<em>Editor Iterator Attribute Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Iterator Attribute Expression</em>'.
   * @generated
   */
  EditorIteratorAttributeExpression createEditorIteratorAttributeExpression();

  /**
   * Returns a new object of class '<em>Editor Iterator Attribute Assignment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Iterator Attribute Assignment</em>'.
   * @generated
   */
  EditorIteratorAttributeAssignment createEditorIteratorAttributeAssignment();

  /**
   * Returns a new object of class '<em>Editor Iterator Attribute Assignment Itr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Iterator Attribute Assignment Itr</em>'.
   * @generated
   */
  EditorIteratorAttributeAssignmentItr createEditorIteratorAttributeAssignmentItr();

  /**
   * Returns a new object of class '<em>Editor Iterator Attribute Assignment Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Iterator Attribute Assignment Node</em>'.
   * @generated
   */
  EditorIteratorAttributeAssignmentNode createEditorIteratorAttributeAssignmentNode();

  /**
   * Returns a new object of class '<em>Editor Iterator Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Iterator Reference</em>'.
   * @generated
   */
  EditorIteratorReference createEditorIteratorReference();

  /**
   * Returns a new object of class '<em>Editor Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Condition</em>'.
   * @generated
   */
  EditorCondition createEditorCondition();

  /**
   * Returns a new object of class '<em>Editor Simple Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Simple Condition</em>'.
   * @generated
   */
  EditorSimpleCondition createEditorSimpleCondition();

  /**
   * Returns a new object of class '<em>Editor Probability</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Probability</em>'.
   * @generated
   */
  EditorProbability createEditorProbability();

  /**
   * Returns a new object of class '<em>Stochastic Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stochastic Function</em>'.
   * @generated
   */
  StochasticFunction createStochasticFunction();

  /**
   * Returns a new object of class '<em>Stochastic Function Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stochastic Function Expression</em>'.
   * @generated
   */
  StochasticFunctionExpression createStochasticFunctionExpression();

  /**
   * Returns a new object of class '<em>Arithmetic Calculation Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arithmetic Calculation Expression</em>'.
   * @generated
   */
  ArithmeticCalculationExpression createArithmeticCalculationExpression();

  /**
   * Returns a new object of class '<em>Arithmetic Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arithmetic Expression</em>'.
   * @generated
   */
  ArithmeticExpression createArithmeticExpression();

  /**
   * Returns a new object of class '<em>String Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Constant</em>'.
   * @generated
   */
  StringConstant createStringConstant();

  /**
   * Returns a new object of class '<em>Editor Condition Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Condition Reference</em>'.
   * @generated
   */
  EditorConditionReference createEditorConditionReference();

  /**
   * Returns a new object of class '<em>Editor Application Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Application Condition</em>'.
   * @generated
   */
  EditorApplicationCondition createEditorApplicationCondition();

  /**
   * Returns a new object of class '<em>Add Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Add Expression</em>'.
   * @generated
   */
  AddExpression createAddExpression();

  /**
   * Returns a new object of class '<em>Mult Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mult Expression</em>'.
   * @generated
   */
  MultExpression createMultExpression();

  /**
   * Returns a new object of class '<em>Exp Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exp Expression</em>'.
   * @generated
   */
  ExpExpression createExpExpression();

  /**
   * Returns a new object of class '<em>Min Max Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Min Max Expression</em>'.
   * @generated
   */
  MinMaxExpression createMinMaxExpression();

  /**
   * Returns a new object of class '<em>One Parameter Arithmetics</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>One Parameter Arithmetics</em>'.
   * @generated
   */
  OneParameterArithmetics createOneParameterArithmetics();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  GTPackage getGTPackage();

} //GTFactory
