/**
 * generated by Xtext 2.25.0
 */
package org.emoflon.ibex.gt.editor.gT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stochastic Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.StochasticFunction#getFunctionExpression <em>Function Expression</em>}</li>
 *   <li>{@link org.emoflon.ibex.gt.editor.gT.StochasticFunction#getParameter <em>Parameter</em>}</li>
 * </ul>
 *
 * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getStochasticFunction()
 * @model
 * @generated
 */
public interface StochasticFunction extends EditorProbability
{
  /**
   * Returns the value of the '<em><b>Function Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Expression</em>' containment reference.
   * @see #setFunctionExpression(StochasticFunctionExpression)
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getStochasticFunction_FunctionExpression()
   * @model containment="true"
   * @generated
   */
  StochasticFunctionExpression getFunctionExpression();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.gt.editor.gT.StochasticFunction#getFunctionExpression <em>Function Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Expression</em>' containment reference.
   * @see #getFunctionExpression()
   * @generated
   */
  void setFunctionExpression(StochasticFunctionExpression value);

  /**
   * Returns the value of the '<em><b>Parameter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter</em>' containment reference.
   * @see #setParameter(ArithmeticExpression)
   * @see org.emoflon.ibex.gt.editor.gT.GTPackage#getStochasticFunction_Parameter()
   * @model containment="true"
   * @generated
   */
  ArithmeticExpression getParameter();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.gt.editor.gT.StochasticFunction#getParameter <em>Parameter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameter</em>' containment reference.
   * @see #getParameter()
   * @generated
   */
  void setParameter(ArithmeticExpression value);

} // StochasticFunction
