/*
 * generated by Xtext 2.27.0
 */
package org.emoflon.ibex.tgg.tggl.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class TGGLProposalProvider extends AbstractTGGLProposalProvider {
	
	@Override
	public void complete_QualifiedName(EObject model, RuleCall ruleCall, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		// TODO Auto-generated method stub
		super.complete_QualifiedName(model, ruleCall, context, acceptor);
	}
	
	@Override
	public void completeSchema_SourceTypes(EObject model, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		// TODO Auto-generated method stub
		super.completeSchema_SourceTypes(model, assignment, context, acceptor);
	}
	
	@Override
	public void completeCorrespondenceType_Source(EObject model, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		// TODO Auto-generated method stub
		super.completeCorrespondenceType_Source(model, assignment, context, acceptor);
	}
}
