/**
 * generated by Xtext 2.27.0
 */
package org.emoflon.ibex.tgg.editor.tgg.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.emoflon.ibex.tgg.editor.tgg.ParamValue;
import org.emoflon.ibex.tgg.editor.tgg.TggPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Param Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ParamValueImpl extends MinimalEObjectImpl.Container implements ParamValue
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParamValueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TggPackage.Literals.PARAM_VALUE;
  }

} //ParamValueImpl
