/**
 * generated by Xtext 2.14.0
 */
package org.emoflon.ibex.tgg.weights.weightDefinition;

import language.TGGRule;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.xbase.XExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule Weight Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.ibex.tgg.weights.weightDefinition.RuleWeightDefinition#getRule <em>Rule</em>}</li>
 *   <li>{@link org.emoflon.ibex.tgg.weights.weightDefinition.RuleWeightDefinition#getWeightCalc <em>Weight Calc</em>}</li>
 * </ul>
 *
 * @see org.emoflon.ibex.tgg.weights.weightDefinition.WeightDefinitionPackage#getRuleWeightDefinition()
 * @model
 * @generated
 */
public interface RuleWeightDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Rule</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rule</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule</em>' reference.
   * @see #setRule(TGGRule)
   * @see org.emoflon.ibex.tgg.weights.weightDefinition.WeightDefinitionPackage#getRuleWeightDefinition_Rule()
   * @model
   * @generated
   */
  TGGRule getRule();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.tgg.weights.weightDefinition.RuleWeightDefinition#getRule <em>Rule</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rule</em>' reference.
   * @see #getRule()
   * @generated
   */
  void setRule(TGGRule value);

  /**
   * Returns the value of the '<em><b>Weight Calc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Weight Calc</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weight Calc</em>' containment reference.
   * @see #setWeightCalc(XExpression)
   * @see org.emoflon.ibex.tgg.weights.weightDefinition.WeightDefinitionPackage#getRuleWeightDefinition_WeightCalc()
   * @model containment="true"
   * @generated
   */
  XExpression getWeightCalc();

  /**
   * Sets the value of the '{@link org.emoflon.ibex.tgg.weights.weightDefinition.RuleWeightDefinition#getWeightCalc <em>Weight Calc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Weight Calc</em>' containment reference.
   * @see #getWeightCalc()
   * @generated
   */
  void setWeightCalc(XExpression value);

} // RuleWeightDefinition
