/**
 * generated by Xtext 2.14.0
 */
package org.emoflon.ibex.tgg.weights.weightDefinition;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.emoflon.ibex.tgg.weights.weightDefinition.WeightDefinitionPackage
 * @generated
 */
public interface WeightDefinitionFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WeightDefinitionFactory eINSTANCE = org.emoflon.ibex.tgg.weights.weightDefinition.impl.WeightDefinitionFactoryImpl.init();

  /**
   * Returns a new object of class '<em>File</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>File</em>'.
   * @generated
   */
  WeightDefinitionFile createWeightDefinitionFile();

  /**
   * Returns a new object of class '<em>Import</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import</em>'.
   * @generated
   */
  Import createImport();

  /**
   * Returns a new object of class '<em>Variable Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable Declaration</em>'.
   * @generated
   */
  VariableDeclaration createVariableDeclaration();

  /**
   * Returns a new object of class '<em>Rule Weight Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule Weight Definition</em>'.
   * @generated
   */
  RuleWeightDefinition createRuleWeightDefinition();

  /**
   * Returns a new object of class '<em>Default Calculation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Default Calculation</em>'.
   * @generated
   */
  DefaultCalculation createDefaultCalculation();

  /**
   * Returns a new object of class '<em>Helper Funtion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Helper Funtion</em>'.
   * @generated
   */
  HelperFuntion createHelperFuntion();

  /**
   * Returns a new object of class '<em>Helper Func Parameter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Helper Func Parameter</em>'.
   * @generated
   */
  HelperFuncParameter createHelperFuncParameter();

  /**
   * Returns a new object of class '<em>Helper Function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Helper Function</em>'.
   * @generated
   */
  HelperFunction createHelperFunction();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  WeightDefinitionPackage getWeightDefinitionPackage();

} //WeightDefinitionFactory
