/*
 * generated by Xtext
 */
package org.moflon.tgg.mosl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TGGAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/moflon/tgg/mosl/parser/antlr/internal/InternalTGG.tokens");
	}
}
