/**
 * generated by Xtext 2.14.0
 */
package org.emoflon.ibex.tgg.weights.weightDefinition.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.emoflon.ibex.tgg.weights.weightDefinition.HelperFuntion;
import org.emoflon.ibex.tgg.weights.weightDefinition.WeightDefinitionPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Helper Funtion</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class HelperFuntionImpl extends MinimalEObjectImpl.Container implements HelperFuntion
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HelperFuntionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WeightDefinitionPackage.Literals.HELPER_FUNTION;
  }

} //HelperFuntionImpl
