/**
 * generated by Xtext 2.14.0
 */
package org.emoflon.ibex.tgg.weights.weightDefinition.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.eclipse.xtext.xbase.XExpression;

import org.emoflon.ibex.tgg.weights.weightDefinition.Import;
import org.emoflon.ibex.tgg.weights.weightDefinition.WeightDefinitionFile;
import org.emoflon.ibex.tgg.weights.weightDefinition.WeightDefinitionPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>File</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.emoflon.ibex.tgg.weights.weightDefinition.impl.WeightDefinitionFileImpl#getImports <em>Imports</em>}</li>
 *   <li>{@link org.emoflon.ibex.tgg.weights.weightDefinition.impl.WeightDefinitionFileImpl#getWeigthDefinitions <em>Weigth Definitions</em>}</li>
 *   <li>{@link org.emoflon.ibex.tgg.weights.weightDefinition.impl.WeightDefinitionFileImpl#getDefault <em>Default</em>}</li>
 *   <li>{@link org.emoflon.ibex.tgg.weights.weightDefinition.impl.WeightDefinitionFileImpl#getHelperFuntions <em>Helper Funtions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WeightDefinitionFileImpl extends MinimalEObjectImpl.Container implements WeightDefinitionFile
{
  /**
   * The cached value of the '{@link #getImports() <em>Imports</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImports()
   * @generated
   * @ordered
   */
  protected Import imports;

  /**
   * The cached value of the '{@link #getWeigthDefinitions() <em>Weigth Definitions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWeigthDefinitions()
   * @generated
   * @ordered
   */
  protected EList<XExpression> weigthDefinitions;

  /**
   * The cached value of the '{@link #getDefault() <em>Default</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefault()
   * @generated
   * @ordered
   */
  protected XExpression default_;

  /**
   * The cached value of the '{@link #getHelperFuntions() <em>Helper Funtions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHelperFuntions()
   * @generated
   * @ordered
   */
  protected EList<XExpression> helperFuntions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WeightDefinitionFileImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WeightDefinitionPackage.Literals.WEIGHT_DEFINITION_FILE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Import getImports()
  {
    return imports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetImports(Import newImports, NotificationChain msgs)
  {
    Import oldImports = imports;
    imports = newImports;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__IMPORTS, oldImports, newImports);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setImports(Import newImports)
  {
    if (newImports != imports)
    {
      NotificationChain msgs = null;
      if (imports != null)
        msgs = ((InternalEObject)imports).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__IMPORTS, null, msgs);
      if (newImports != null)
        msgs = ((InternalEObject)newImports).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__IMPORTS, null, msgs);
      msgs = basicSetImports(newImports, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__IMPORTS, newImports, newImports));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<XExpression> getWeigthDefinitions()
  {
    if (weigthDefinitions == null)
    {
      weigthDefinitions = new EObjectContainmentEList<XExpression>(XExpression.class, this, WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__WEIGTH_DEFINITIONS);
    }
    return weigthDefinitions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public XExpression getDefault()
  {
    return default_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDefault(XExpression newDefault, NotificationChain msgs)
  {
    XExpression oldDefault = default_;
    default_ = newDefault;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__DEFAULT, oldDefault, newDefault);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDefault(XExpression newDefault)
  {
    if (newDefault != default_)
    {
      NotificationChain msgs = null;
      if (default_ != null)
        msgs = ((InternalEObject)default_).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__DEFAULT, null, msgs);
      if (newDefault != null)
        msgs = ((InternalEObject)newDefault).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__DEFAULT, null, msgs);
      msgs = basicSetDefault(newDefault, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__DEFAULT, newDefault, newDefault));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<XExpression> getHelperFuntions()
  {
    if (helperFuntions == null)
    {
      helperFuntions = new EObjectContainmentEList<XExpression>(XExpression.class, this, WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__HELPER_FUNTIONS);
    }
    return helperFuntions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__IMPORTS:
        return basicSetImports(null, msgs);
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__WEIGTH_DEFINITIONS:
        return ((InternalEList<?>)getWeigthDefinitions()).basicRemove(otherEnd, msgs);
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__DEFAULT:
        return basicSetDefault(null, msgs);
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__HELPER_FUNTIONS:
        return ((InternalEList<?>)getHelperFuntions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__IMPORTS:
        return getImports();
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__WEIGTH_DEFINITIONS:
        return getWeigthDefinitions();
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__DEFAULT:
        return getDefault();
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__HELPER_FUNTIONS:
        return getHelperFuntions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__IMPORTS:
        setImports((Import)newValue);
        return;
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__WEIGTH_DEFINITIONS:
        getWeigthDefinitions().clear();
        getWeigthDefinitions().addAll((Collection<? extends XExpression>)newValue);
        return;
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__DEFAULT:
        setDefault((XExpression)newValue);
        return;
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__HELPER_FUNTIONS:
        getHelperFuntions().clear();
        getHelperFuntions().addAll((Collection<? extends XExpression>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__IMPORTS:
        setImports((Import)null);
        return;
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__WEIGTH_DEFINITIONS:
        getWeigthDefinitions().clear();
        return;
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__DEFAULT:
        setDefault((XExpression)null);
        return;
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__HELPER_FUNTIONS:
        getHelperFuntions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__IMPORTS:
        return imports != null;
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__WEIGTH_DEFINITIONS:
        return weigthDefinitions != null && !weigthDefinitions.isEmpty();
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__DEFAULT:
        return default_ != null;
      case WeightDefinitionPackage.WEIGHT_DEFINITION_FILE__HELPER_FUNTIONS:
        return helperFuntions != null && !helperFuntions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //WeightDefinitionFileImpl
