/*
 * generated by Xtext 2.27.0
 */
package org.emoflon.ibex.common.slimgt.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.contentassist.PrefixMatcher;
import org.emoflon.ibex.common.slimgt.ide.highlighting.SlimGTSemanticHighlightingCalculator;
import org.emoflon.ibex.common.slimgt.ui.contentassist.MyFQNPrefixMatcher;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SlimGTUiModule extends AbstractSlimGTUiModule {

	public SlimGTUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends PrefixMatcher> bindPrefixMatcher() {
		return MyFQNPrefixMatcher.class;
	}
	
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator () {
		return SlimGTSemanticHighlightingCalculator.class;
	}
}
