/*
 * generated by Xtext 2.27.0
 */
package org.emoflon.ibex.common.slimgt.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SlimGTUiModule extends AbstractSlimGTUiModule {

	public SlimGTUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
