/*
 * generated by Xtext
 */
package org.moflon.tgg.mosl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.moflon.tgg.mosl.ui.internal.TGGActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TGGExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TGGActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TGGActivator.getInstance().getInjector(TGGActivator.ORG_MOFLON_TGG_MOSL_TGG);
	}
	
}
